[[icedos.repositories]]
url = "github:icedos/apps"
modules = [
  "android-tools",
  "bash",
  "btop",
  "celluloid",
  "codium",
  "direnv",
  # "faugus-launcher",
  "gamemode",
  "gamescope",
  "git",
  "kitty",
  "lact",
  "lsfg-vk",
  "mangohud",
  "nautilus",
  "nh",
  "nix-health",
  "nix",
  "nixfmt",
  "ssh",
  "steam",
  "toolset",
  "zenergy",
  "zenstates",
  "zsh",
]

[[icedos.repositories]]
url = "github:icedos/desktop"
modules = ["adwaita-qt", "clear-xdg-portals", "displays", "gdm"]

[[icedos.repositories]]
url = "github:icedos/hardware"
modules = [
  "bluetooth",
  "disable-ipv6",
  "graphics",
  "kernel",
  "monitors",
  "mounts",
  "pipewire",
  "radeon",
  "ryzen",
  "systemd-boot",
  "uinput",
  "upower",
  "zram",
]

[[icedos.repositories]]
url = "github:icedos/gnome"

[[icedos.repositories]]
url = "github:icedos/tweaks"
modules = ["gaming", "kernel"]

[[icedos.repositories]]
url = "github:icedos/users"

[[icedos.repositories]]
url = "github:icedos/providers"
modules = ["chaotic"]

[icedos.applications]
defaultBrowser = "librewolf.desktop"
defaultEditor = "codium.desktop"
extraPackages = [
  # Emulators
  # "cemu", # Wii U
  "duckstation", # PS1
  # "heroic", # Epic Games Store
  "pcsx2", # PS2
  "ppsspp", # PSP
  "rpcs3", # PS3

  "appimage-run",
  "bottles",
  "gsound", # Small library for playing system sounds (required to show file properties in Nautilus)
  "mousai", # Song recognizer
  "spotify", # Music streaming service
  "ungoogled-chromium", # Chromium with dependencies on Google web services removed
  "qbittorrent", # BitTorrent client
  "warp",
]
insecurePackages = []

[icedos.applications.codium.users.giannis]
autoSave = "onFocusChange"
formatOnPaste = false

[icedos.applications.git.users.giannis]
username = "giannisgalleti"
email = "giannispapanatsios@yahoo.gr"

[icedos.applications.mangohud]
fpsLimit = "144,60,0"

[icedos.applications.nh.gc]
days = 7 # Number of days before a generation can be deleted
generations = 5 # Number of generations that will always be kept

[icedos.applications.steam]
beta = true
downloadsWorkaround = true

[icedos.desktop.gnome]
titlebarLayout = "appmenu:minimize,maximize,close"

[icedos.desktop.gnome.extensions]
arcmenu = true
dashToPanel = true

# [icedos.desktop.gnome.users.giannis]
# startupScript = "steam & signal-desktop"

[icedos.desktop.gnome.users.giannis.pinnedApps.arcmenu]
enable = true
list = [
  "codiumIDE.desktop",
  "org.duckstation.DuckStation.desktop",
  "PCSX2.desktop",
  "ppsspp.desktop",
  "rpcs3.desktop",
  "smartcode-stremio.desktop",
  "OpenRGB.desktop",
  "com.usebottles.bottles.desktop",
  "io.github.lact-linux.desktop",
  "io.missioncenter.MissionCenter.desktop",
  "io.github.seadve.Mousai.desktop",
  "onlyoffice-desktopeditors.desktop",
]

[icedos.desktop.gnome.users.giannis.pinnedApps.shell]
enable = true
list = ["steam.desktop", "signal-desktop.desktop", "librewolf.desktop"]

[icedos.desktop.gnome.clock]
date = true
weekday = true

[icedos.desktop.users.giannis]

[icedos.desktop.users.giannis.idle.lock]
enable = false

[icedos.desktop.users.giannis.idle.disableMonitors]
seconds = 3600

[icedos.desktop.users.giannis.idle.suspend]
enable = false

[icedos.hardware.bootloaders.systemd-boot]
mountPoint = "/boot"

[icedos.hardware.kernel]
version = "latest"

[[icedos.hardware.monitors]]
name = "DP-2"
resolution = "2560x1440"
refreshRate = 144
position = "0x0"

[[icedos.hardware.mounts]]
path = "/"
device = "/dev/disk/by-uuid/051448c2-f19b-4d84-b91b-f38d494996a5"
fsType = "btrfs"
flags = ["compress=zstd", "nofail", "x-gvfs-show"]

[[icedos.hardware.mounts]]
path = "/mnt/C"
device = "/dev/disk/by-uuid/6C383F39383F021E"
fsType = "ntfs"
flags = ["nofail", "x-gvfs-show"]

[[icedos.hardware.mounts]]
path = "/mnt/D"
device = "/dev/disk/by-uuid/5cf83e52-be67-1c2a-a5f8-72c38068e1f0"
fsType = "btrfs"
flags = ["compress=zstd", "nofail", "x-gvfs-show"]

[[icedos.hardware.mounts]]
path = "/mnt/HDD"
device = "/dev/disk/by-uuid/42B629A5B6299B05"
fsType = "ntfs"
flags = ["nofail", "x-gvfs-show"]

[icedos.system]
version = "24.05"

[icedos.users.giannis]
description = "Giannis"
